- id: echo
  name: echo
  entry: echo
  language: python
  'types': [ python ]

- id: autopep8
  name: autopep8
  entry: autopep8
  language: python
  'types': [python]
  args: ["-i"]

- id: flake8
  name: flake8
  entry: flake8
  language: python
  'types': [python]
  args: ["--max-line-length 100"]

