- id: echo
  name: echo
  entry: echo
  language: python
  'types': [ python ]

- id: autopep8
  name: autopep8
  entry: autopep8
  language: python
  'types': [python]
  args: ["-i"]

- id: autoflake
  name: autoflake
  entry: autoflake
  language: python
  'types': [python]
  args: ["-ir", "--remove-all-unused-imports", "--remove-unused-variables", "--ignore-init-module-imports"]

- id: flake8
  name: flake8
  entry: flake8
  language: python
  'types': [python]
  args: ["--max-line-length 100"]

